In [1]:
import os
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# This allows the notebook to find the 'pysafer' folder in the parent directory
# sys.path.append(os.path.abspath('..'))

import pySAFER
print(f"Location of the package: {pySAFER.__file__}")
print(f"helpers.py exist or not: {os.path.exists(os.path.join(os.path.dirname(pySAFER.__file__), 'helpers.py'))}")
# from pySAFER.helpers import calc_ndvi,

Location of the package: C:\GitHub\pySAFER\src\pySAFER\__init__.py
helpers.py exist or not: True

In [3]:
file_point_sample = r"C:\GitHub\pySAFER\Examples\point_samples.txt"
df = pd.read_csv(file_point_sample, sep='\t', parse_dates=['date'])
display(df.head(3))

year = df['year']
doy = df['doy']
lat = df['lat']
tmax = df['Tmax']
tmin = df['Tmin']
red = df['red']
nir = df['nir']

        date  year  doy        lat  Tmax  Tmin   red   nir
0 2025-05-01  2025  121  37.365888  38.0  21.2  0.03  0.36
1 2025-05-02  2025  122  37.365888  38.1  21.3  0.03  0.36
2 2025-05-03  2025  123  37.365888  38.2  21.4  0.03  0.36

In [5]:
df['ra'] = pySAFER.calc_ra(lat, doy, year)
ra = df['ra']
df['rs'] = pySAFER.calc_incoming_solar_radiation(ra, rs_obs=None, tmax=tmax, tmin=tmin, coastal=True)
rs = df['rs']
display(df.head(3))

,date,year,doy,lat,Tmax,Tmin,red,nir,ra,rs
0,2025-05-01,2025,121,37.365888,38.0,21.2,0.03,0.36,38.091586,29.664518
1,2025-05-02,2025,122,37.365888,38.1,21.3,0.03,0.36,38.239313,29.779563
2,2025-05-03,2025,123,37.365888,38.2,21.4,0.03,0.36,38.384086,29.892308

In [9]:
df['ndvi'] = pySAFER.calc_ndvi(red, nir)
display(df.head(3))

,date,year,doy,lat,Tmax,Tmin,red,nir,ra,ndvi
0,2025-05-01,2025,121,37.365888,38.0,21.2,0.03,0.36,38.091586,0.846154
1,2025-05-02,2025,122,37.365888,38.1,21.3,0.03,0.36,38.239313,0.846154
2,2025-05-03,2025,123,37.365888,38.2,21.4,0.03,0.36,38.384086,0.846154